#version: '3.9'

services:
  blog:
    build: .
    container_name: blog_container
    ports:
      - "8010:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads
    env_file:
      - .env