services:
  - type: web
    name: fiskalisti
    env: docker
    plan: free
    branch: main
    region: frankfurt
    buildCommand: ""
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn blog.wsgi:application"

    